#version 460
//#extension GL_EXT_ray_tracing : require
#include "../CommonShaders/rayPipelineCommonStruct.glsl"

//WhittedStyleRayTracing
// const int RAY_PER_PIXEL = 1;
// const int BOUNCE_LIMIT  = 5;
// const int MAX_PATHS = 8;

//PathTracing
const int RAY_PER_PIXEL = 1;
//spp=16，噪点应该是spp=1的四分之一
const int BOUNCE_LIMIT  = 8;
const int MAX_PATHS = 8;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D resultImage;
layout(location = 0) rayPayloadEXT PrimaryPayload primaryPayload;
layout(set = 0, binding = 1) uniform accelerationStructureEXT topLevelAS;

layout(set = 0, binding = 4) uniform GlobalBufferObject {
    mat4 mainCameraView;
    mat4 mainCameraViewInverse;
    mat4 mainCameraProj;
    mat4 mainCameraProjInverse; 
    vec3 mainCameraPos;
    float tanHalfFovY;
    float aspect;
    float padding[58];
} globalUBO;

layout(set = 0, binding = 5) uniform CustomBufferObject {
    int frameCount;
    uint cameraInMotion;
    uint lightCount;
    uint materialCount;

    uint renderMode;      // 0 = Whitted, 1 = Path Tracing, 2 = ReSTIR(未实现), 3 = Bidirectional(未实现)
    uint spp;             // Samples Per Pixel
    uint maxBounce;       // 最大反弹次数
    uint accumulate;      // 0 = 不积累, 1 = 帧间积累
    uint randomSeed;      // 可选，每次运行不同

    float rrProbability;   //RR（俄罗斯轮盘）
    uint enableNEE;
    uint useSky;
    float maxRadiance;
    uint debugMode;
} customUBO;

//不要加 writeonly，因为既要 imageLoad() 又要 imageStore()。
//rgba32f（用rgba16f会有精度误差）用于保存 HDR 累积值。
//resultImage 仍然是最终显示用。
// TODO:
// RGBA16F accumulation exhibits progressive darkening after ~100 frames.
// RGBA32F works correctly.
// Investigate whether this is due to numerical error,
// synchronization, or driver-specific behavior.
layout(set = 0, binding = 8, rgba32f) uniform image2D accumulationImage; 

void main(){
    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    ivec2 size = ivec2(gl_LaunchSizeEXT.xy);

    vec3 accumulatedRadiance = vec3(0.0);

    //int pathCount = 0;//test

    for (int s = 0; s < RAY_PER_PIXEL; ++s){
        vec2 jitter = rnd2(pixel, s, customUBO.frameCount);
        vec2 uv = (vec2(pixel) + jitter) / vec2(size);
        vec2 ndc = uv * 2.0 - 1.0;

        // 如有需要再开
        // ndc.y = -ndc.y;

        vec4 viewDirH = globalUBO.mainCameraProjInverse * vec4(ndc, 1.0, 1.0);
        vec3 rayDir = normalize(
            (globalUBO.mainCameraViewInverse * vec4(normalize(viewDirH.xyz), 0.0)).xyz
        );
        vec3 rayOrigin = globalUBO.mainCameraPos;

        vec3 lightColor = vec3(0.0);

        //const int MAX_PATHS = 8;
        PathState pathStack[MAX_PATHS];
        int stackSize = 0;

        pathStack[stackSize++] = PathState(
            rayOrigin,
            rayDir,
            vec3(1.0),
            1.0, //ior
            vec3(0.0),   // mediumEntryPos
            0u,           // insideMedium=0，假设一开始在空气里
            0u //depth
        );

        //primaryPayload.radiance = vec3(0.0);
        primaryPayload.sampleIndex = s;

        while(stackSize > 0){
            PathState path = pathStack[--stackSize];

            primaryPayload.radiance = vec3(0.0);
            primaryPayload.throughput = path.throughput;
            primaryPayload.spawnRayCount = 0u;
            primaryPayload.done = 0u;
            primaryPayload.currentIOR = path.currentIOR;
            primaryPayload.insideMedium = path.insideMedium;
            primaryPayload.mediumEntryPos = path.mediumEntryPos;

            traceRayEXT(
                topLevelAS,
                0, //gl_RayFlagsOpaqueEXT,
                0xFF,
                0, 1, 0,
                path.origin,
                EPSILON,
                path.direction,
                1e32,
                0
            );
            //path.throughput = vec3(1.0);//test
            accumulatedRadiance += path.throughput * primaryPayload.radiance;

            if(path.depth + 1u >= BOUNCE_LIMIT) continue;

            if(primaryPayload.spawnRayCount >= 1u && stackSize < MAX_PATHS){
                PathState nextPath;
                nextPath.origin = primaryPayload.nextRayOrigin0;
                nextPath.direction = primaryPayload.nextRayDir0;
                nextPath.throughput = path.throughput * primaryPayload.nextRayThroughputMul0;
                nextPath.depth = path.depth + 1u;
                nextPath.currentIOR = primaryPayload.nextCurrentIOR0;
                nextPath.mediumEntryPos = primaryPayload.nextMediumEntryPos0;
                nextPath.insideMedium = primaryPayload.nextInsideMedium0;
                pathStack[stackSize++] = nextPath;
            }

            if(primaryPayload.spawnRayCount >= 2u && stackSize < MAX_PATHS){
                PathState secondPath;
                secondPath.origin = primaryPayload.nextRayOrigin1;
                secondPath.direction = primaryPayload.nextRayDir1;
                secondPath.throughput = path.throughput * primaryPayload.nextRayThroughputMul1;
                secondPath.depth = path.depth + 1u;
                secondPath.currentIOR = primaryPayload.nextCurrentIOR1;
                secondPath.mediumEntryPos = primaryPayload.nextMediumEntryPos1;
                secondPath.insideMedium = primaryPayload.nextInsideMedium1;
                pathStack[stackSize++] = secondPath; //for WhittedStyleRayTracing only
            }
        }//stack
    }//spp

    vec3 frameRadiance = accumulatedRadiance / float(RAY_PER_PIXEL);

    //non-accumulate image
    //imageStore(resultImage, pixel, vec4(frameRadiance, 1.0).bgra); //有噪点
    //return;


    // EMA
    //float alphaEMA = 0.1;

    // Running Average
    float alphaRA = 1.0 / (customUBO.frameCount + 1);
    //float alphaRA = 1.0 / (10 + 1); //test：固定frameCount 有噪点，但是不变暗
    //alphaRA = max(alphaRA,0.0025);//test 16位的时候0.002会缓慢变暗

    // Running Average
    vec3 prevColor = imageLoad(accumulationImage, pixel).bgr;
    vec3 accumColor;
    if(customUBO.frameCount == 0) 
        accumColor = frameRadiance;
    else 
        accumColor = prevColor + (frameRadiance - prevColor) * alphaRA;
    imageStore(accumulationImage, pixel, vec4(accumColor, 1.0).bgra);
    imageStore(resultImage,       pixel, vec4(accumColor, 1.0).bgra);

}