#version 460
#extension GL_EXT_ray_tracing : require

#include "../CommonShaders/rayPipelineCommon.glsl"

const int RAY_PER_PIXEL = 4;
const int BOUNCE_LIMIT  = 1;   // 至少给到 3~4，1 的话看不到真正多次 bounce
const int FRAME_INDEX   = 1;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D resultImage;
layout(set = 0, binding = 1) uniform accelerationStructureEXT topLevelAS;
layout(location = 0) rayPayloadEXT PrimaryPayload primaryPayload;

layout(set = 0, binding = 6) uniform GlobalBufferObject {
    mat4 mainCameraView;
    mat4 mainCameraViewInverse;
    mat4 mainCameraProj;
    mat4 mainCameraProjInverse; 
    vec3 mainCameraPos;
    float tanHalfFovY;
    float aspect;
    float padding[58];
} globalUBO; //store camera and view information

layout(set = 0, binding = 7) uniform CustomBufferObject {
    int frameCount;
    bool cameraInMotion;
    uint triangleCount;
    uint materialCount;
} customUBO;

void main(){

    // if(customUBO.cameraInMotion){ //test customUBO
    //     imageStore(resultImage, ivec2(gl_LaunchIDEXT.xy), vec4(0.0, 1.0, 0.0, 1.0));
    //     return;
    // }

    ivec2 pix  = ivec2(gl_LaunchIDEXT.xy);
    ivec2 size = ivec2(gl_LaunchSizeEXT.xy);

    vec3 finalColor = vec3(0.0);

    for (int s = 0; s < RAY_PER_PIXEL; ++s)
    {
        vec2 jitter = rnd2(pix, s, FRAME_INDEX);
        vec2 uv = (vec2(pix) + jitter) / vec2(size);

        vec2 ndc = uv * 2.0 - 1.0;

        // 如果你的图像空间和 Vulkan NDC Y 方向不一致，保留这一句
        //ndc.y = -ndc.y;

        // 从 NDC -> view space
        vec4 viewDirH = globalUBO.mainCameraProjInverse * vec4(ndc, 1.0, 1.0);

        // 只取方向，不要平移
        vec3 rayDir = normalize(
            (globalUBO.mainCameraViewInverse * vec4(normalize(viewDirH.xyz), 0.0)).xyz
        );

        // ray origin 用相机世界坐标
        vec3 rayOrigin = globalUBO.mainCameraPos;


        // uv = uv * 2.0 - 1.0;

        // vec3 rayOrigin = vec3(0.0, 0.0, -7.0);
        // vec3 rayDir    = normalize(vec3(uv.x, -uv.y, 1.5));

        vec3 lightColor = vec3(0.0);

        primaryPayload.throughput = vec3(1.0);
        primaryPayload.radiance   = vec3(0.0);
        primaryPayload.nextOrigin = rayOrigin;
        primaryPayload.nextDir    = rayDir;
        primaryPayload.done       = 0u;

        for (int bounce = 0; bounce < BOUNCE_LIMIT; ++bounce)
        {
            primaryPayload.radiance = vec3(0.0);
            primaryPayload.done     = 0u;

            traceRayEXT( //primary ray
                topLevelAS,
                gl_RayFlagsOpaqueEXT,
                0xFF,
                0,   // sbtRecordOffset
                1,   // sbtRecordStride
                0,   // missIndex
                rayOrigin,
                0.001,
                rayDir,
                10000.0,
                0    // primary payload location
            );
            //Notes:
            //SBTRecordStride 的意思是：同一次 trace 里，SBT hit record 之间按“几组一跳”来索引。
            //它不是字节步长，而是“记录编号的步长”概念 。
            //SBT hit 区是按 primary / shadow 两个 record 成对排的，所以一条 ray 要跨过另一条 ray type 的 record，索引步长自然就是 2。


            
            //lightColor += primaryPayload.radiance;//NEW! 这里直接加 radiance，不要再乘 throughput
            lightColor += primaryPayload.throughput * primaryPayload.radiance;

            if (primaryPayload.done != 0u) break;

            // 推进到下一跳
            //rayOrigin = primaryPayload.nextOrigin;//NEW!
            //rayDir    = normalize(primaryPayload.nextDir);//NEW!

            // //NEW! 可选：俄罗斯轮盘前的简单终止条件，防止很暗的路径浪费
            //if (max(primaryPayload.throughput.r, max(primaryPayload.throughput.g, primaryPayload.throughput.b)) < 0.001) break;
            
        }

        finalColor += lightColor;
    }

    finalColor /= float(RAY_PER_PIXEL);
    imageStore(resultImage, pix, vec4(finalColor, 1.0).bgra);
}