#version 460
#extension GL_EXT_ray_tracing : require

hitAttributeEXT vec2 attribs;//只想判断有没有打中并上色 时，可以先不依赖它。


// const vec3 sphereCenter = vec3(1.5, 0.0, 0.0); //TODO: pass from host
// const float sphereRadius = 1.0; //TODO
// const vec3 sphereCenter1 = vec3(0.0, 0.0, 1.5); //TODO: pass from host
// const float sphereRadius1 = 0.5; //TODO 把上述变成数组


const vec3 sphereCenters[3] = vec3[]( //TODO: pass from host
    vec3(1.5, 0, 0),
    vec3(0.0, 1.5, 0.0),
    vec3(-1.5, -1.5, 1.5)
);

const float sphereRadii[3] = float[]( //TODO: pass from host
    1.0,
    0.5,
    1.5
);

void main() {
    uint sphereId = gl_InstanceCustomIndexEXT;
    vec3 sphereCenter = sphereCenters[sphereId];
    float sphereRadius = sphereRadii[sphereId];

    vec3 oc = gl_ObjectRayOriginEXT - sphereCenter;
    vec3 rd = gl_ObjectRayDirectionEXT;

    float a = dot(rd, rd);
    float b = 2.0 * dot(oc, rd);
    float c = dot(oc, oc) - sphereRadius * sphereRadius;
    float disc = b * b - 4.0 * a * c;

    if (disc < 0.0) return;

    float s = sqrt(disc);
    float t0 = (-b - s) / (2.0 * a);
    float t1 = (-b + s) / (2.0 * a);

    float t = t0;
    if (t < gl_RayTminEXT || t > gl_RayTmaxEXT) t = t1;
    if (t < gl_RayTminEXT || t > gl_RayTmaxEXT) return;

    reportIntersectionEXT(t, 0);
}