#version 450
#include "../CommonShaders/rayUBO.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

/***************************
* Constants
***************************/
const int BOUNCE_LIMIT = 5;
const int RAY_PER_PIXEL = 10;
const bool ENABLE_BVH = true;
#include "../CommonShaders/rayTracing.glsl"

layout(set = 0, binding = 0) uniform GlobalBufferObject {
    mat4 mainCameraView;
    mat4 mainCameraViewInverse;
    mat4 mainCameraProj;
    mat4 mainCameraProjInverse; 
    vec3 mainCameraPos;
    float tanHalfFovY;
    float aspect;
    float padding[58];
} globalUBO; //store camera and view information

layout(set = 0, binding = 1, std430) readonly buffer SBOIn {
   vec4 pixels[];
} sboIn; //use for frame accumulate

layout(set = 0, binding = 2, std430) buffer SBOOut {
   vec4 pixels[];
} sboOut; //use for frame accumulate

//binding 3~9 is in rayUBO.glsl, for ray tracing uniforms

layout(set = 0, binding = 10, rgba8) uniform writeonly image2D resultImage;

void main(){
    // ----------------------------
    // 1. Pixel cord conver to NDC(0..1)
    ivec2 gridSize = ivec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(gridSize); //normalizedCoord

    // ----------------------------
    // 2. Convert to NDC [-1, 1]
    float x_ndc = uv.x * 2.0 - 1.0;
    float y_ndc = uv.y * 2.0 - 1.0;

    // ----------------------------
    // 3. Project to camera space
    vec3 dir_cam = normalize(vec3(
        x_ndc * globalUBO.aspect * globalUBO.tanHalfFovY,
        y_ndc * globalUBO.tanHalfFovY,
        1.0 //!not -1, because we want camera to look positive z direction
    ));
    //dir_cam = normalize(vec3(0,0,1.0));//!!!

    // ----------------------------
    // 4. Convert to world space
    Ray ray;
    vec4 clip_coord = vec4(x_ndc, y_ndc, -1.0, 1.0);
    vec4 view_coord = globalUBO.mainCameraProjInverse * clip_coord;
    //view_coord = clip_coord;//!!!
    view_coord = vec4(view_coord.xy, -1.0, 0.0);
    vec4 world_coord = globalUBO.mainCameraViewInverse * view_coord;
    //world_coord = view_coord;//!!!
    ray.dir = normalize(world_coord.xyz);
    ray.origin = globalUBO.mainCameraPos;
    //ray.origin = vec3(0,0,1);//!!!
    
    // ----------------------------
    // 5. Current Frame Color
    //uint state = gl_GlobalInvocationID.x ^ gl_GlobalInvocationID.y ^ customUBO.frameCount;
    uint state = gl_GlobalInvocationID.x;
    state = state * 747796405u + gl_GlobalInvocationID.y;
    state = state * 747796405u + customUBO.frameCount;
    state = state * 747796405u + 2891336453u;
    
    vec3 birghtness_score_sum = vec3(0.0);
    for(int i = 0; i < RAY_PER_PIXEL; i++)
        birghtness_score_sum += TraceRay(ray, state);

    vec3 currentFrameColor = birghtness_score_sum / RAY_PER_PIXEL;

    // ----------------------------
    // 6. Accumulate
    uint index = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;

    if(customUBO.cameraInMotion){ //use 5 bounce, 10 rays per pixel
        sboOut.pixels[index] = vec4(currentFrameColor, 1.0); //disable accumulate when camera in motion; it can be used to increase performance
    }else{
        float alpha = 0.01f; //smaller alpha will take more time to stable, but need less ray per pixel, use 10 ray per pixel(500 fps)
        sboOut.pixels[index] = vec4(currentFrameColor, 1.0) * alpha + sboIn.pixels[index] * (1.0 - alpha);
    }
    //float alpha = 0.05f; //need more ray per pixel, if use 20 ray per pixel(250 fps), but stable faster

    
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), sboOut.pixels[index].bgra);

    //imageStore( resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(currentFrameColor, 1.0)); //no accumulate
    //imageStore( resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(sboMaterial.materials[1].reflectance, sboMaterial.materials[1].reflectance, sboMaterial.materials[1].reflectance, 1.0));
    //imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(0.0, 0.0, 0.5, 1.0));
    //imageStore( resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(sboBVHNode.nodes[0].left, 1, 1, 1.0));
    
}